# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2964171c3584ef9ae296dc6e1e2acc51ada064813daefdd46f018f2dce902e669424ca29e2e98f1726839fdb6fdf6bd1273788e9803c4947b3900b5168a2600

test:
  secret_key_base: 121d60d6866fe16e3ca0aaf5f1a3afb4c9673a0162d29c8e72a60a3134eb351ac907ed508669dd513bd63b338b10f84ccead2def5bccbdbd167b6f364ec26663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
